version: '3'

networks:
  demo:
    driver: 'bridge'

services:
  redis:
    image: redis:latest
    command: [ "redis-server", "--bind", "redis", "--port", "6379" ]
    networks:
      - demo

  # The Database
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    container_name: demo_sql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - ${DB_DOCKER_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_RANDOM_ROOT_PASSWORD: "false"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - demo

  app:
    container_name: demo_product
    build:
      context: ./docker
    working_dir: /var/www/html/project
    volumes:
      - ${PROJECT_PATH}:/var/www/html/project
    ports:
      - ${PROJECT_PORT}:80
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    networks:
      - demo
    env_file: .env
    extra_hosts:
      - "web.demo.localhost:127.0.0.1"

volumes:
  db_data: {}
